steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-usage-analytics-pipeline:latest', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-usage-analytics-pipeline:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-usage-analytics-pipeline'
      - '--image=gcr.io/$PROJECT_ID/ai-usage-analytics-pipeline:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--concurrency=1'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=BIGQUERY_DATASET=ai_usage_analytics'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=DEBUG=false'
      - '--port=8080'

timeout: 1200s